# Generated by Django 4.2.1 on 2023-06-12 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('blog_slug', models.CharField(max_length=100, verbose_name='slug')),
                ('blog_content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('blog_preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('blog_created_at', models.DateField(default=datetime.date.today, verbose_name='создан')),
                ('blog_is_publicated', models.BooleanField(default=False, verbose_name='опубликован')),
                ('blog_views_count', models.BigIntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('blog_title',),
            },
        ),
    ]
